#!/usr/bin/env bash
##
##	Author: Joseph Mills joseph@ihinfiniteautomation.com
##	Copyright: Infinite Automation all rights reserved,
##

verbose=0
upgradeArgument="All"
now=$(date +"%m-%d-%Y %r"); 
logFile="$MA_HOME"/logs/ma-script.log;

scriptChecker(){
	if [ -z "$MA_HOME" ]; 
	then
		echo "Do not execute this file directly."
		echo "Run \'ma start\'  instead."
		exit 1;
	fi
}